# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170529_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(null=True),
        ),
    ]
