# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170529_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
